# data_download
destination_folder: "data/01_raw"  # Utilisé pour le stockage temporaire avant l'upload MinIO
xls_path: "data/01_raw"
csv_path: "data/02_intermediate"

# data_preprocessing
path_annual: data/02_intermediate/
path_tempo: data/02_intermediate/

# training
train:
  target: "Consommation"
  use_optuna: true
  n_trials: 30
  run_name: "xgboost_run"
  validation_type: "time_series_cv"
  walkforward_initial_train_size: 3000
  walkforward_test_size: 24
  threshold_rmse: 300
  model_params:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 6